package com.benhsoan.domain.auth;

public enum Permission {
    // User
    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,
    USER_ASSIGN_ROLE,

    // Patient
    PATIENT_CREATE,
    PATIENT_READ,
    PATIENT_UPDATE,
    PATIENT_DELETE,

    // Medical Record
    RECORD_CREATE,
    RECORD_READ,
    RECORD_UPDATE,
    RECORD_DELETE,
    RECORD_UPDATE_STATUS,

    // Prescription
    PRESCRIPTION_CREATE,
    PRESCRIPTION_READ,
    PRESCRIPTION_UPDATE,
    PRESCRIPTION_DELETE,
    PRESCRIPTION_UPDATE_STATUS,

    // Appointment
    APPOINTMENT_CREATE,
    APPOINTMENT_READ,
    APPOINTMENT_UPDATE,
    APPOINTMENT_DELETE,

    // Vital Sign
    VITAL_SIGN_CREATE,
    VITAL_SIGN_READ,
    VITAL_SIGN_UPDATE,

    // Diagnosis
    DIAGNOSIS_CREATE,
    DIAGNOSIS_READ,
    DIAGNOSIS_UPDATE,

    // Pharmacy
    PHARMACY_CREATE,
    PHARMACY_READ,
    PHARMACY_UPDATE,
    PHARMACY_DELETE,

    // Invoice
    INVOICE_CREATE,
    INVOICE_READ,
    INVOICE_UPDATE,
    INVOICE_DELETE,

    // Audit
    AUDIT_READ,

    // Role & Permission
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    PERMISSION_READ
}
