# ==========================================================
# Production Environment
# ==========================================================

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================================
# Hibernate
# ==========================================================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

# ==========================================================
# Flyway
# ==========================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================================================
# JWT
# ==========================================================

app.jwt.secret=${JWT_SECRET}

app.jwt.expiration-ms=${JWT_EXPIRATION:1800000}

# ==========================================================
# Mail
# ==========================================================

spring.mail.host=${MAIL_HOST}

spring.mail.port=${MAIL_PORT}

spring.mail.username=${MAIL_USERNAME}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================================
# Logging
# ==========================================================

logging.level.root=WARN
logging.level.com.benhsoan=WARN
logging.level.org.springframework.security=WARN