# ==========================================
# Cấu hình môi trường Development
# ==========================================

# ---- Server ----
server.port=8080

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/digital_medical_record?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2

spring.datasource.username=4P69BFC6JLkjWKN.root

spring.datasource.password=YOUR_PASSWORD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.com.benhsoan=DEBUG
logging.level.org.springframework.web=DEBUG

